### PR TITLE
Added reference to docpad = @docpad. 

### PR DESCRIPTION
**Pull request by jeffa00**
Seems to be needed with latest update to docpad.

Tagcloud was working for me until I updated docpad to version 6.65.0 at which point trying to run docpad resulted in an error that docpad was undefined in the tagcloud plugin.

Adding the reference seems to fix the issue.

### CODE REVIEW

**Comment by hatashiro** [comment]
+1

**Comment by rantecki** [comment]
Thanks Jeff.  Will publish new version shortly.

**Comment by jeffa00** [comment]
No problem. Love the plug in.

**Comment by tvjames** [comment]
Hi, love the plugin as well. Just wondering when a release with this fix might be hitting npm? Cheers

**Comment by rantecki** [comment]
Apologies for my tardiness.  A new version (2.0.1) has been published.

**Comment by tvjames** [comment]
No apology needed, thanks for the plugin :)

**Pull request merged**
